# Generated by Django 4.1.7 on 2023-02-23 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_order_cart_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cart_items',
            new_name='products',
        ),
    ]
