# Generated by Django 4.1.7 on 2023-03-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='weight',
            field=models.SmallIntegerField(default=0),
        ),
    ]
