# Generated by Django 4.1.7 on 2023-03-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='static/images/products_img/default.jpg', upload_to='static/images/products_img'),
        ),
    ]
