# Generated by Django 4.1.7 on 2023-03-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='app/static/images/products_img/default.jpg', upload_to='app/static/images/products_img'),
        ),
    ]
